#!/usr/bin/env bash
# Concatenate every per-directory README in build-sequence order into one file.
# Output: MEGA-README.md at repo root (gitignored — local navigation aid only).
# Usage:  bash scripts/build-mega-readme.sh

set -euo pipefail

cd "$(dirname "$0")/.."
OUT="MEGA-README.md"

# Order matches the journey: top-level → 1 → 2 → 3 → 4 → 5 → docs → historical.
# mk312-bt2/ is a separate nested repo and is skipped intentionally.
READMES=(
  "README.md"
  "1-order-boards/README.md"
  "2-order-parts/README.md"
  "3-build-and-flash/README.md"
  "3-build-and-flash/firmware/README.md"
  "4-wireless/README.md"
  "4-wireless/bluetooth/README.md"
  "4-wireless/wifi/README.md"
  "4-wireless/wifi/pcb/jlcpcb-package/README.md"
  "5-software/README.md"
  "docs/troubleshooting/README.md"
  "historical/README.md"
)

{
  echo "# MK-312BT — Mega README"
  echo
  echo "_Auto-generated by \`scripts/build-mega-readme.sh\` on $(date '+%Y-%m-%d %H:%M %Z'). Do not edit by hand — edits won't survive the next regeneration. Edit the source READMEs instead._"
  echo
  echo "**Source files (in order):**"
  echo
  for f in "${READMES[@]}"; do
    echo "- [\`$f\`](#$(echo "$f" | tr '[:upper:]/.' '[:lower:]--'))"
  done
  echo
  echo "---"
  echo

  for f in "${READMES[@]}"; do
    if [[ ! -f "$f" ]]; then
      echo "> ⚠️  Missing: \`$f\` (skipped)"
      echo
      continue
    fi
    anchor=$(echo "$f" | tr '[:upper:]/.' '[:lower:]--')
    echo "<a id=\"$anchor\"></a>"
    echo
    echo "# 📄 \`$f\`"
    echo
    cat "$f"
    echo
    echo
    echo "---"
    echo
  done
} > "$OUT"

lines=$(wc -l < "$OUT" | tr -d ' ')
size=$(du -h "$OUT" | cut -f1)
echo "Wrote $OUT ($lines lines, $size)"
